In [19]:
Exercici1='''
La temperatura d'una planxa de metall plana ve donada per la funció
         T(x,y)=(100)/((x**2)+(y^2)-(2*x)-(2*y)+6)

(a) Quina és la temperatura del punt P=(0,0) i en quina direcció va el flux de calor en aquest punt?
(b) On es troba la font de calor (és a dir el punt de temperatura màxima) i quina és la seva temperatura?
(c) Quins són els punts del cercle x^2+y^2 ≤ 1 amb temperatura màxima i mínima?
'''
print(Exercici1)



#Importo diferents llibreries i començo a definir les variables i la funció de la temperatura
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from colorama import Fore, Style

''' Definim què són variables '''
x, y = sp.symbols('x y')

''' Defineixo la funció de temperatura '''
T_funcio = 100 / ((x**2) + (y**2) - (2*x) - (2*y) + 6)


La temperatura d'una planxa de metall plana ve donada per la funció
         T(x,y)=(100)/((x**2)+(y^2)-(2*x)-(2*y)+6)

(a) Quina és la temperatura del punt P=(0,0) i en quina direcció va el flux de calor en aquest punt?
(b) On es troba la font de calor (és a dir el punt de temperatura màxima) i quina és la seva temperatura?
(c) Quins són els punts del cercle x^2+y^2 ≤ 1 amb temperatura màxima i mínima?



In [3]:
# Primer apartat
T_P=T_funcio.subs({x:0, y:0})                                #Evaluem la funció en el punt que ens han donat, només hem de definir el valor de les variables (x:0,y:0)

gradient_T=[sp.diff(T_funcio, x), sp.diff(T_funcio, y)]      #Fem el gradient de la funció temperatura, és a dir, les derivades parcials per cada direcció

flux=[g.subs({x:0, y:0}) for g in gradient_T]                #Aqui hem agafat el gradient i hem substituït les variables (x:0,y:0).  Aquesta direcció no està malament, pero fem millor l'unitari
flux_mag=sp.sqrt(sum(f**2 for f in flux))                    #La suma dels quadrats de les variables ha de ser ser igual a 1 (x**2+y**2=1)
flux_unitari=[f/flux_mag for f in flux]                      #Vector unitari


ApartatA="RESULTATS DE L'APARTAT (a)"
Ample=80
print()
print(ApartatA.center(Ample))
print("La temperatura del punt P(0,0) és", T_P, "i la direcció del flux és", flux_unitari)    #No poso directament el vector perque queda millor imprimir-lo amb sp.pprint 
print( )         


                           RESULTATS DE L'APARTAT (a)                           
La temperatura del punt P(0,0) és 50/3 i la direcció del flux és [sqrt(2)/2, sqrt(2)/2]



In [5]:
# Segon apartat
'''El punt de temperatura màxima és aquell en que el gradient s'anul·la. He d'obtenir un valor per la variable x i un altre valor 
per la variable y, que després l'utilitzarem per saber la temperatura en aquell punt'''
solucio=sp.solve(gradient_T, (x,y))                            #Aqui estem ressolent el sistema d'equacions que s'obté quan igualem el grandient de la temperatura a 0
T_max=T_funcio.subs(solucio)                                   #Agafem la funció de la temperatura i la evaluem en el punt trobat en la linea d'abans

ApartatB="RESULTATS DE L'APARTAT (b)"
print( )
print(ApartatB.center(Ample))
print("La font de calor es troba en", solucio, "i té una temperatura", T_max, "u")      #L'exericicio no indica les unitats de temperatura
print( )


                           RESULTATS DE L'APARTAT (b)                           
La font de calor es troba en {x: 1, y: 1} i té una temperatura 25 u



In [7]:
# Tercer apartat
''' Com estem parlant d'una circumferència, la variable y es pot expressar en termes de l'altre variable: y = ±sqrt(1 - x^2) '''
y_pos=sp.sqrt(1-x**2)
y_neg=-sp.sqrt(1-x**2)

''' Ara fem la funció temperatura extigui expressada només per la variable x, però tindrem dues funcions (una per cada posible valor de y) '''
T_positiu=T_funcio.subs(y, y_pos)
T_negatiu=T_funcio.subs(y, y_neg)

''' Fem les primeres derivades, aquestes ens donaran els punts crítics '''
dTdx_pos=sp.diff(T_positiu, x)
dTdx_neg=sp.diff(T_negatiu, x)

''' Trobar els punts crítics en la frontera '''
x_crit_pos=sp.solve(dTdx_pos, x)
x_crit_pos=x_crit_pos[0]
x_crit_neg=sp.solve(dTdx_neg, x)
x_crit_neg=x_crit_neg[0]

''' Les coordenades dels punts crítics, calcular la component y '''
y_crit_pos=sp.sqrt(1 - x_crit_pos**2)
y_crit_neg=-sp.sqrt(1 - x_crit_neg**2)


ApartatC="RESULTATS DE L'APARTAT (c)"
Ample=80
print( )
print(ApartatC.center(Ample))


''' Segona derivada per x_crit_pos. La funció ha de ser diferent de zero, i si és negativa correspondrà a la temperatura màxima. 
Si és un valor positiu, és el punt de la planxa de menor temperatura ''' 
d2Tdx2_pos=sp.diff(dTdx_pos, x)
punt_critic_pos=d2Tdx2_pos.subs(x, x_crit_pos)

if punt_critic_pos > 0:
    T_minima_pos = T_positiu.subs(x, x_crit_pos).evalf()
    print(f"La temperatura mínima és {T_minima_pos:.2f}u, i és en el punt ( {x_crit_pos} , {y_crit_pos} )")
elif punt_critic_pos < 0:
    T_maxima_pos = T_positiu.subs(x, x_crit_pos).evalf()
    print(f"La temperatura máxima és {T_maxima_pos:.2f}u, i és en el punt ( {x_crit_pos} , {y_crit_pos })")

   
''' Segona derivada per x_crit_negatiu, a l'igual que abans '''
d2Tdx2_neg=sp.diff(dTdx_neg, x)
punt_critic_neg=d2Tdx2_neg.subs(x, x_crit_neg)

if punt_critic_neg > 0:
    T_minima_neg = T_negatiu.subs(x, x_crit_neg).evalf()
    print(f"La temperatura mínima és {T_minima_neg:.2f}u, i és en el punt ( {x_crit_neg} , {y_crit_neg} )")
elif punt_critic_neg < 0:
    T_maxima_neg = T_negatiu.subs(x, x_crit_neg).evalf()
    print(f"La temperatura máxima és {T_maxima_neg:.2f}u, i és en el punt ( {x_crit_neg} , {y_crit_neg} )")

print( )


                           RESULTATS DE L'APARTAT (c)                           
La temperatura máxima és 23.97u, i és en el punt ( sqrt(2)/2 , sqrt(2)/2)
La temperatura mínima és 10.17u, i és en el punt ( -sqrt(2)/2 , -sqrt(2)/2 )



In [21]:
Exercici_matrius='''
S'ha definit la següent matriu de transformació en 𝑅³:

                                      |  2  -1   0 |
                                A  =  | -1   2  -1 |
                                      |  0  -1   2 |

Apartat 1: Propietats básiques de la matriu
a) Calcula el determinant de A
b) Calcula la traça de la matriu A
c) Troba la inversa (si existeix)

Apartat 2: Vector i valors propis
d) Calcula els valors propis de A
e) Calcula els vectors propis associats
f) Ordena els valors i els vector propis

Apartat 3: Diagonalització
    - Demostra que la matriu es pot diagonalitzar

Apartat 4: Operacions
g) Fes la resta B-A, sent B:
                                      | -5   1  -3 |
                                B  =  | -1   0   0 |
                                      |  0  -1  -5 |

h) Eleva A al quadrat i al cub.
'''

print(Exercici_matrius)


S'ha definit la següent matriu de transformació en 𝑅³:

                                      |  2  -1   0 |
                                A  =  | -1   2  -1 |
                                      |  0  -1   2 |

Apartat 1: Propietats básiques de la matriu
a) Calcula el determinant de A
b) Calcula la traça de la matriu A
c) Troba la inversa (si existeix)

Apartat 2: Vector i valors propis
d) Calcula els valors propis de A
e) Calcula els vectors propis associats
f) Ordena els valors i els vector propis

Apartat 3: Diagonalització
    - Demostra que la matriu es pot diagonalitzar

Apartat 4: Operacions
g) Fes la resta B-A, sent B:
                                      | -5   1  -3 |
                                B  =  | -1   0   0 |
                                      |  0  -1  -5 |

h) Eleva A al quadrat i al cub.



In [11]:
# Primer cal definir la matriu A
A=np.array([[2,-1,0] , [-1,2,-1] , [0,-1,2]])        #Els vectors es posen en columnes, de manera que queda una matriu 3x3


''' APARTAT A '''
determinant=np.linalg.det(A)           # Primer faré el determinant de la matriu
traça=np.trace(A)                      # Ara la traça de la matriu
inversa=np.linalg.inv(A)               # Això dona la inversa de la matriu

# Pasem a imprimir tots els resultats de l'apartat
print("APARTAT A".center(50,"-"))
print( )
print("a) El determinant dona", determinant)
print( )
print("b) La traça de la matriu és", traça)
print( )
print("c) La inversa de la matriu és")
print(inversa)

--------------------APARTAT A---------------------

a) El determinant dona 4.0

b) La traça de la matriu és 6

c) La inversa de la matriu és
[[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]


In [13]:
''' APARTAT B '''
valors_propis, vectors_propis=np.linalg.eig(A)              # Podem calcular els valors i vector propis directament
estats_propis=list(zip(valors_propis,vectors_propis.T))     # Posem el vector propi a cada valor propi i aquests vector propis els hem fet la transposada (en comptes de columna, passen a ser una linea)
estats_propis.sort(key=lambda x: x[0])                      # Ordena la llista però segons els valors propis

# Pasem a imprimir tots els resultats de l'apartat
print("APARTAT B".center(50,"-"))
print( )
for k in range(len(estats_propis)):                         # És un bucle que primer agafa tots els estats propis i els dona un index que el marca com k (si son 3 estats propis, k = 0,1,2 )
    print(f"Estat propi {k}")
    print(f"Valor propi: {valors_propis[k]}")
    print(f"Vector propi: {vectors_propis[:,k]}")
    print( )

--------------------APARTAT B---------------------

Estat propi 0
Valor propi: 3.4142135623730923
Vector propi: [-0.5         0.70710678 -0.5       ]

Estat propi 1
Valor propi: 2.0
Vector propi: [-7.07106781e-01  5.09486455e-16  7.07106781e-01]

Estat propi 2
Valor propi: 0.5857864376269046
Vector propi: [0.5        0.70710678 0.5       ]



In [15]:
''' APARTAT C '''
P=vectors_propis                   # Matriu dels vectors propis
D=np.diag(valors_propis)           # Matriu diagonal amb els valors propis

#Comprovem que es pot diagonlitzar A = P D P^(-1)
P_inversa=np.linalg.inv(P)         # P^(-1)
A_diagonalitzacio=P@D@P_inversa    # Multiplicació matricial, és la manera de comprovar que A és diagonalitzable
A_diagonalitzacio_aprox=np.round(A_diagonalitzacio, decimals=10)

# Pasem a imprimir tots els resultats de l'apartat
print("APARTAT C".center(50,"-"))
print( )
print("Matriu de vectors propis (P):")
print(P)
print("\nMatriu diagonal (D):")
print(D)
print("\nMatriu reconstruida amb la formula (A):")
print(A_diagonalitzacio_aprox)

--------------------APARTAT C---------------------

Matriu de vectors propis (P):
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  5.09486455e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]

Matriu diagonal (D):
[[3.41421356 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.58578644]]

Matriu reconstruida amb la formula (A):
[[ 2. -1. -0.]
 [-1.  2. -1.]
 [-0. -1.  2.]]


In [17]:
''' APARTAT D '''
# Defineixo la matriu B com ho he fet amb la matriu A en el primer apartat
B=np.array([[-5,-1,0] , [1,0,-1] , [-3,0,-5]]) 

#Operacions 
restaAB=A-B                #Resta, si fos suma només caldria posar +
quadrat=np.matmul(A,A)     #També es pot fer A@A o np.linalg.matrix_power(A,"c") on "c" es la potencia que podem utilitzar aquesta comanda per fer el cub
cub=np.linalg.matrix_power(A, 3)



print("g) La resta de les dues matrius dona")
print(restaAB)
print( )
print("i) El quadrat de la matriu, fent una multiplicació matricial, i no elevant al quadrat els elements com A**2, és")
print(quadrat)
print("En canvi el cub de la matriu és")
print(cub)

g) La resta de les dues matrius dona
[[ 7  0  0]
 [-2  2  0]
 [ 3 -1  7]]

i) El quadrat de la matriu, fent una multiplicació matricial, i no elevant al quadrat els elements com A**2, és
[[ 5 -4  1]
 [-4  6 -4]
 [ 1 -4  5]]
En canvi el cub de la matriu és
[[ 14 -14   6]
 [-14  20 -14]
 [  6 -14  14]]
